blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/yuxelmurat/Lumia.PM/discussions
    about: For general questions and discussions about Lumia.PM
  - name: Contact us
    url: mailto:help@lumiapm.com
    about: Reach the Lumia.PM team directly
